name: Build HTML5 and deploy

on: 
  push:
    branches: 
      - 'main'

jobs:
  compile:
    name: Build HTML5 and deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ilammy/msvc-dev-cmd@v1.4.1
      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.1.5

      - run: haxelib install lime
      - run: haxelib install openfl
      - run: haxelib install flixel
      - run: haxelib install flixel-tools
      - run: haxelib install flixel-addons
      - run: haxelib install flixel-ui
      - run: haxelib install hscript
      - run: haxelib install newgrounds
      - run: haxelib git polymod https://github.com/larsiusprime/polymod.git
      - run: haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc
      - run: haxelib run lime build html5 

      - name: Output build
        uses: JamesIves/github-pages-deploy-action@v4.3.0
        with:
          branch: gh-pages
          folder: export/release/html5/bin