name: Build Windows

on: [push]

jobs:
  compile:
    name: Compile windows
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.1.5

      - run: haxelib install lime
      - run: haxelib install openfl
      - run: haxelib install flixel
      - run: haxelib install flixel-tools
      - run: haxelib install flixel-addons
      - run: haxelib install flixel-ui
      - run: haxelib install hscript
      - run: haxelib install newgrounds
      - run: haxelib git polymod https://github.com/larsiusprime/polymod.git
      - run: haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc
      - run: lime build windows 

      - name: Output build
        uses: actions/upload-artifact@v3
        with:
          name: Game
          path: export/windows